package com.ekakashi.greenhouse.features.weather.object_weather;

/**
 * Created by nquochuy on 3/8/2018.
 */

public enum EnumTemplateType {
    WEATHER,
    TEMPERATURE,
    HUMIDITY,
    WIND_DIRECTION,
    WIND_VELOCITY,
    PRECIPITATION,
    AMOUNT_OF_INSOLATION,
    INSOLATION_FORECAST_3_DAYS,
    INSOLATION_FORECAST_8_DAYS,
    WEATHER_FORECAST_2_DAYS,
    TEMPERATURE_FORECAST_2_DAYS,
    HUMIDITY_FORECAST_2_DAYS,
    WIND_DIRECTION_FORECAST_2_DAYS,
    WIND_VELOCITY_FORECAST_2_DAYS,
    PRECIPITATION_FORECAST_2_DAYS,
    WEATHER_FORECAST_8_DAYS,
    TEMPERATURE_FORECAST_8_DAYS,
    HUMIDITY_FORECAST_8_DAYS,
    WIND_DIRECTION_FORECAST_8_DAYS,
    WIND_VELOCITY_FORECAST_8_DAYS,
    PRECIPITATION_FORECAST_8_DAYS,
    WEATHER_HISTORY,
    TEMPERATURE_HISTORY,
    HUMIDITY_HISTORY,
    WIND_DIRECTION_HISTORY,
    WIND_VELOCITY_HISTORY,
    PRECIPITATION_HISTORY,
    INSOLATION_HISTORY,
    SUNRISE,
    SUNSET
    }
